name: dayselection
description: A Flutter package that provides a customizable day-of-week selector widget, useful for schedules, reminders, and calendar apps.
version: 1.0.0+5

homepage: https://github.com/akprajapati5004/dayselection.git
repository: https://github.com/akprajapati5004/dayselection.git
issue_tracker: https://github.com/akprajapati5004/dayselection/issues.git

#environment:
#  sdk: ^3.8.1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
